# Generates the UMAP cluster visualization.
# Regenerates the UMAP cluster scatter plot used in the research paper.
# Run this if data/final/figures/umap_clusters.png is missing.
# Requires: data/final/clusters.json (generated by analysis/cluster.py)

import json
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import numpy as np

with open('data/final/clusters.json', encoding='utf-8') as f:
    data = json.load(f)

profs  = data['professors']
x      = [p['umap_x'] for p in profs]
y      = [p['umap_y'] for p in profs]
clust  = [p['cluster_id'] for p in profs]

my_pos = data['my_position']
my_x   = my_pos['umap_x']
my_y   = my_pos['umap_y']

labels = {
    0: 'PL / Architecture / SE',
    1: 'Scientific Computing / AI / Graphics',
    2: 'AI / Agents / NLP',
    3: 'AI / ML / Robotics',
    4: 'ML / Algorithms / Bio',
    5: 'OS / Networking / Cloud',
    6: 'CS Education / HCI',
    7: 'Quantum / Theory',
    8: 'ML / NLP / Data Science',
    9: 'Security / Privacy'
}

colors = plt.cm.tab10(np.linspace(0, 1, 10))
fig, ax = plt.subplots(figsize=(11, 7))

for cid in range(10):
    mask = [i for i, c in enumerate(clust) if c == cid]
    ax.scatter(
        [x[i] for i in mask],
        [y[i] for i in mask],
        c=[colors[cid]],
        label=f'C{cid}: {labels[cid]}',
        alpha=0.6,
        s=18
    )

ax.scatter(
    my_x, my_y, c='red', s=150, zorder=5,
    marker='*', label='Your Research Interest'
)

ax.set_title(
    'Research Landscape — UMAP + KMeans (768 CS Faculty, 10 Clusters)',
    fontsize=12
)
ax.set_xlabel('UMAP Dimension 1')
ax.set_ylabel('UMAP Dimension 2')
ax.legend(fontsize=7, loc='upper left', framealpha=0.8)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig('data/final/figures/umap_clusters.png', dpi=150, bbox_inches='tight')
print('Saved: data/final/figures/umap_clusters.png')
